apiVersion: v1
kind: Service
metadata:
  name: jenkins
 # annotations:
 #   metallb.universe.tf/address-pool: production-public-ips
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: jenkins
  type: LoadBalancer